:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.

| `409 Conflict`
| 클라이언트의 요청이 서버의 상태와 충돌이 발생한 경우.
|===

[[snippets-write-convention]]
== snippets 작성 컨벤션
domain-httpRequestCode-etc

== 회원
=== 회원 가입
operation::user-post[snippets='curl-request,http-request,http-response,request-fields,response-fields']

=== 회원 가입 (중복 회원)
operation::user-post-duplicate[snippets='curl-request,http-request,http-response,request-fields,response-fields']

=== 회원 가입 (파라미터 오류)
operation::user-post-invalidParameter[snippets='curl-request,http-request,http-response,request-fields']

=== 모든 회원 조회
operation::user-get-allUser[snippets='curl-request,http-request,http-response,response-fields']

=== 단일 회원 조회
operation::user-get[snippets='curl-request,http-request,http-response,path-parameters,response-fields']

=== 단일 회원 (없는 회원)
operation::user-get-notExist[snippets='curl-request,http-request,http-response,path-parameters']

=== 회원 수정
operation::user-patch[snippets='curl-request,http-request,http-response,path-parameters,request-fields,response-fields']

=== 회원 수정 (없는 회원)
operation::user-patch-notExist[snippets='curl-request,http-request,http-response,path-parameters,request-fields,response-fields']

=== 회원 삭제
operation::user-delete[snippets='curl-request,http-request,http-response,path-parameters']

=== 회원 삭제 (없는 회원)
operation::user-delete-notExist[snippets='curl-request,http-request,http-response,path-parameters']