server.port: 0

spring:
  application:
    name: user-service

  cloud:
    # Spring Config Setting
    config:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Actuator Setting
management.endpoints.web.exposure.include: busrefresh, health

logging.level:
  com.ecommerce: DEBUG