server.port: 0

spring:
  application:
    name: user-service

  cloud:
    # Spring Config Setting
    config:
      enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Actuator Setting
management.endpoints.web.exposure.include: busrefresh, health

logging.level:
  com.ecommerce: DEBUG