server.port: 0

spring:
  application:
    name: order-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    default_batch_fetch_size: 1000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Actuator Setting
management.endpoints.web.exposure.include: busrefresh, health

logging.level:
  com.ecommerce: DEBUG
  org.hibernate.type: trace