server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
          filters:
            - RewritePath=/catalog-service/(?<segment>.*),/$\{segment}
        - id: frontend-service
          uri: lb://FRONTEND-SERVICE
          predicates:
            - Path=/frontend-service/**
          filters:
            - RewritePath=/frontend-service/(?<segment>.*),/$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*),/$\{segment}

    # Spring Config Setting
    config:
      enabled: false

# Actuator Setting
management.endpoints.web.exposure.include: busrefresh, health
